# docker-compose.yml
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: home-noc-api:latest
    container_name: home-noc-api
    restart: unless-stopped
    env_file:
      - backend/.env.example
      - backend/.env # optional, override secrets locally
    ports:
      - "8000:8000"
    volumes:
      - api_data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  api_data:
